spring:
  datasource:
    url: Server=tcp:tejas.database.windows.net,1433;Initial Catalog=tejas;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    username: tejas
    password: Password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080
  
  
